//go:build linux

package check

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// Supported reports whether the live check works on this OS.
const Supported = true

// Run checks the local Linux system.
func Run() []Result {
	var out []Result
	svc := Result{Area: "Audit service", Item: "auditd running", Want: "active",
		Affects: "Logons, sudo, account changes and audit integrity (without it, only auth.log is available)"}
	b, _ := exec.Command("systemctl", "is-active", "auditd").Output()
	svc.Have = strings.TrimSpace(string(b))
	if svc.Have == "active" {
		svc.Status = Pass
	} else {
		svc.Status = Fail
		svc.Fix = "install auditd (apt install auditd, or dnf install audit) and run systemctl enable --now auditd"
		if svc.Have == "" {
			svc.Have = "not installed"
		}
	}
	out = append(out, svc)
	if svc.Status == Pass {
		rules, rerr := exec.Command("auditctl", "-l").Output()
		status, _ := exec.Command("auditctl", "-s").Output()
		if rerr != nil {
			out = append(out, Result{Area: "Audit rules", Item: "auditctl -l", Status: Error,
				Have: "could not read the loaded rules (run as root)", Want: "readable"})
		} else {
			out = append(out, EvaluateAuditRules(string(rules), string(status))...)
		}
		if conf, err := os.ReadFile("/etc/audit/auditd.conf"); err == nil {
			out = append(out, EvaluateAuditdConf(ParseAuditdConf(string(conf)))...)
		}
	}
	if cl, err := os.ReadFile("/proc/cmdline"); err == nil {
		out = append(out, EvaluateCmdline(string(cl)))
	}
	sys := Result{Area: "System log", Item: "Kernel and udisks messages kept", Want: "syslog file or persistent journal",
		Affects: "USB & Removable Media (device details and who mounted them)"}
	switch {
	case exists("/var/log/syslog"):
		sys.Status, sys.Have = Pass, "/var/log/syslog"
	case exists("/var/log/messages"):
		sys.Status, sys.Have = Pass, "/var/log/messages"
	case exists("/var/log/journal"):
		sys.Status, sys.Have = Pass, "persistent systemd journal"
	default:
		sys.Status, sys.Have = Fail, "journal is not persistent (lost at reboot)"
		sys.Fix = "mkdir -p /var/log/journal && systemctl restart systemd-journald"
	}
	out = append(out, sys)
	return out
}

func exists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

// MissingRulesLive returns the recommended rules this system does not
// already have loaded, ready to save as RulesFile, and whether the loaded
// rules are locked until reboot (-e 2). Rules from an earlier RulesFile are
// kept, so saving the output again never drops them.
func MissingRulesLive() (text string, locked bool, err error) {
	loaded, err := exec.Command("auditctl", "-l").Output()
	if err != nil {
		return "", false, fmt.Errorf("could not read the loaded audit rules (run as root): %w", err)
	}
	status, _ := exec.Command("auditctl", "-s").Output()
	locked = strings.Contains(string(status), "enabled 2")

	// Rules loaded from our own file count as missing, so they stay in it.
	ours := map[string]bool{}
	if b, err := os.ReadFile(RulesFile); err == nil {
		for _, l := range strings.Split(string(b), "\n") {
			if r, ok := parseAuditRule(l); ok {
				ours[ruleKey(r)] = true
			}
		}
	}
	var others []string
	for _, l := range strings.Split(string(loaded), "\n") {
		if r, ok := parseAuditRule(l); ok && !ours[ruleKey(r)] {
			others = append(others, l)
		}
	}
	missing := MissingRules(AuditRules, strings.Join(others, "\n"), exists)

	var b strings.Builder
	b.WriteString("## Blackbox: audit rules this system did not already have.\n")
	b.WriteString("## Generated by \"blackbox check --audit-rules --missing\"; rules already loaded\n")
	b.WriteString("## (under any key) were left out. Save as " + RulesFile + " (mode 0600).\n")
	for _, l := range missing {
		b.WriteString(l + "\n")
	}
	if !locked {
		b.WriteString("## Lock the rules until reboot (the STIG requires this).\n-e 2\n")
	}
	return b.String(), locked, nil
}
